"use client";

import { Ban, Check, MessageSquareOff, PauseCircle, Plus, ShieldAlert } from "lucide-react";
import { useState } from "react";
import styles from "./admin-dashboard.module.css";

type Report = { id: string; reason: string; status: string; created_at: string; reported_user_id: string; room_message_id: string | null; direct_message_id: string | null; reporter?: { username: string; display_name: string } | null; reported?: { username: string; display_name: string } | null; room_message?: { content: string; created_at: string } | null; direct_message?: { content: string; created_at: string } | null };
type Room = { id: string; name: string; slug: string; is_active: boolean };
export function AdminDashboard({ reports: initial, rooms: initialRooms, stats }: { reports: Report[]; rooms: Room[]; stats: { users: number; roomMessages: number; directMessages: number } }) {
  const [reports, setReports] = useState(initial); const [rooms, setRooms] = useState(initialRooms); const [notice, setNotice] = useState("");
  async function act(body: Record<string, unknown>) { const response = await fetch("/api/admin/moderation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); setNotice(response.ok ? "Moderation action completed." : payload.error); return response.ok; }
  async function resolve(id: string) { if (await act({ action: "resolve_report", reportId: id })) setReports((items) => items.map((item) => item.id === id ? { ...item, status: "resolved" } : item)); }
  async function toggle(room: Room) { if (await act({ action: "toggle_room", roomId: room.id, active: !room.is_active })) setRooms((items) => items.map((item) => item.id === room.id ? { ...item, is_active: !item.is_active } : item)); }
  async function addRoom() { const name = prompt("Room name"); if (!name) return; const slug = name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); if (await act({ action: "create_room", name, slug, description: `A public space for ${name.toLowerCase()}.` })) location.reload(); }
  return <div className="admin-stack">{notice && <div className="notice">{notice}</div>}<div className="stats-grid"><div><span>Members</span><strong>{stats.users}</strong></div><div><span>Room messages</span><strong>{stats.roomMessages}</strong></div><div><span>Private messages</span><strong>{stats.directMessages}</strong></div><div><span>Open reports</span><strong>{reports.filter((item) => item.status === "open").length}</strong></div></div><section className="manager-section"><div className="manager-heading"><div><span className="kicker">Safety queue</span><h2>Reports</h2></div><ShieldAlert /></div><div className="report-list">{reports.map((report) => { const reportedMessage = report.room_message ?? report.direct_message; return <article key={report.id}><div><strong>{report.reported?.display_name || "Reported member"}</strong><span>@{report.reported?.username || "unknown"} · reported by @{report.reporter?.username || "member"}</span>{reportedMessage && <blockquote className={styles.reportedMessage} aria-label="Reported message">{reportedMessage.content}</blockquote>}<p>{report.reason}</p><small>{new Date(report.created_at).toLocaleString()} · {report.status}</small></div><div><button onClick={() => void act({ action: "mute_user", userId: report.reported_user_id, hours: 24 })}><PauseCircle size={14} /> Mute 24h</button><button onClick={() => void act({ action: "suspend_user", userId: report.reported_user_id })}><Ban size={14} /> Suspend</button>{report.room_message_id && <button onClick={() => void act({ action: "delete_room_message", messageId: report.room_message_id })}><MessageSquareOff size={14} /> Remove message</button>}{report.direct_message_id && <button onClick={() => void act({ action: "delete_direct_message", messageId: report.direct_message_id })}><MessageSquareOff size={14} /> Remove private message</button>}<button onClick={() => void resolve(report.id)}><Check size={14} /> Resolve</button></div></article>; })}{!reports.length && <p className="empty-line">No reports in the queue.</p>}</div></section><section className="manager-section"><div className="manager-heading"><div><span className="kicker">Community spaces</span><h2>Public rooms</h2></div><button onClick={() => void addRoom()}><Plus size={15} /> Add room</button></div><div className="room-admin-list">{rooms.map((room) => <div key={room.id}><span><strong>#{room.name}</strong><small>{room.slug}</small></span><button onClick={() => void toggle(room)}>{room.is_active ? "Pause" : "Activate"}</button></div>)}</div></section></div>;
}
