"use client";

import { CornerUpLeft, Edit3, Flag, LoaderCircle, Send, SmilePlus, Trash2 } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Avatar } from "@/components/app-frame";
import { createClient } from "@/lib/supabase/client";

type Profile = { id: string; username: string; display_name: string; avatar_url: string | null };
type Message = { id: string; conversation_id: string; sender_id: string; content: string; created_at: string; updated_at: string; reply_to_id: string | null; profiles: Profile | null; message_reactions?: Array<{ id: string; emoji: string; user_id: string }> };
export function DirectChat({ conversationId }: { conversationId: string }) {
  const supabase = useMemo(() => createClient(), []); const bottomRef = useRef<HTMLDivElement>(null); const channelRef = useRef<ReturnType<NonNullable<typeof supabase>["channel"]> | null>(null); const typingTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const [viewerId, setViewerId] = useState(""); const [other, setOther] = useState<Profile | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [content, setContent] = useState(""); const [reply, setReply] = useState<Message | null>(null); const [typing, setTyping] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!supabase) return; const { data } = await supabase.from("direct_messages").select("id,conversation_id,sender_id,content,created_at,updated_at,reply_to_id,profiles!direct_messages_sender_id_fkey(id,username,display_name,avatar_url),message_reactions(id,emoji,user_id)").eq("conversation_id", conversationId).is("deleted_at", null).order("created_at").limit(100); setMessages((data as unknown as Message[]) ?? []); setTimeout(() => bottomRef.current?.scrollIntoView({ behavior: "smooth" }), 20); }, [conversationId, supabase]);
  useEffect(() => { if (!supabase) { setLoading(false); return; } let channel: ReturnType<typeof supabase.channel> | null = null; void supabase.auth.getUser().then(async ({ data }) => { const user = data.user; if (!user) { setLoading(false); return; } setViewerId(user.id); const { data: members } = await supabase.from("direct_conversation_members").select("user_id,profiles!direct_conversation_members_user_id_fkey(id,username,display_name,avatar_url)").eq("conversation_id", conversationId); const member = members?.find((entry) => entry.user_id !== user.id); setOther((member?.profiles as unknown as Profile) ?? null); await load(); await supabase.from("direct_conversation_members").update({ last_read_at: new Date().toISOString() }).eq("conversation_id", conversationId).eq("user_id", user.id); channel = supabase.channel(`dm:${conversationId}`).on("postgres_changes", { event: "*", schema: "public", table: "direct_messages", filter: `conversation_id=eq.${conversationId}` }, () => void load()).on("broadcast", { event: "typing" }, ({ payload }) => { if (payload.user_id !== user.id) { setTyping(true); setTimeout(() => setTyping(false), 1800); } }).subscribe(); channelRef.current = channel; setLoading(false); }); return () => { if (channel) void supabase.removeChannel(channel); }; }, [conversationId, load, supabase]);
  function announceTyping() { if (!channelRef.current || !viewerId) return; if (typingTimer.current) clearTimeout(typingTimer.current); void channelRef.current.send({ type: "broadcast", event: "typing", payload: { user_id: viewerId } }); typingTimer.current = setTimeout(() => {}, 900); }
  async function send(event: FormEvent) { event.preventDefault(); if (!content.trim()) return; const response = await fetch("/api/messages/direct", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ conversationId, content, replyToId: reply?.id ?? null }) }); const payload = await response.json(); if (!response.ok) setError(payload.error); else { setContent(""); setReply(null); await load(); } }
  async function remove(message: Message) { if (!confirm("Delete this message?")) return; await fetch(`/api/messages/direct/${message.id}`, { method: "DELETE" }); await load(); }
  async function edit(message: Message) { const next = prompt("Edit your message", message.content); if (!next) return; const response = await fetch(`/api/messages/direct/${message.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: next }) }); if (!response.ok) setError((await response.json()).error); else await load(); }
  async function react(message: Message) { if (!supabase || !viewerId) return; await supabase.from("message_reactions").upsert({ direct_message_id: message.id, user_id: viewerId, emoji: "✨" }, { onConflict: "direct_message_id,user_id,emoji" }); await load(); }
  async function report(message: Message) { if (!supabase || !viewerId) return; const reason = prompt("Why should moderators review this message? (at least 10 characters)"); if (!reason || reason.trim().length < 10) return; const { error: reportError } = await supabase.from("reports").insert({ reporter_id: viewerId, reported_user_id: message.sender_id, direct_message_id: message.id, reason }); setError(reportError?.message || "Report sent privately to moderators."); }
  if (loading) return <div className="state-card"><LoaderCircle className="spin" /> Opening private conversation…</div>; if (!supabase) return <div className="state-card error-state">Connect Supabase to use direct messages.</div>; if (!viewerId) return <div className="state-card"><strong>Sign in to view this conversation.</strong><a className="primary-button" href="/sign-in">Sign in</a></div>;
  return <div className="chat-surface"><header className="chat-heading">{other && <Avatar name={other.display_name} image={other.avatar_url} />}<div><h1>{other?.display_name || "Private conversation"}</h1><p>{other ? `@${other.username}` : "Only members can read this conversation"}</p></div><span>Participant-only access</span></header><div className="message-stream">{messages.map((message) => <article className={`message ${message.sender_id === viewerId ? "own-message" : ""}`} key={message.id}><Avatar name={message.profiles?.display_name || "Member"} image={message.profiles?.avatar_url ?? null} /><div className="message-body">{message.reply_to_id && <span className="reply-label"><CornerUpLeft size={12} /> Reply</span>}<div className="message-meta"><strong>{message.profiles?.display_name}</strong><time>{new Date(message.created_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time>{message.updated_at !== message.created_at && <small>(edited)</small>}</div><p>{message.content}</p>{Boolean(message.message_reactions?.length) && <div className="reaction-list"><button>✨ {message.message_reactions?.length}</button></div>}</div><div className="message-actions"><button onClick={() => setReply(message)} aria-label="Reply"><CornerUpLeft size={14} /></button><button onClick={() => void react(message)} aria-label="React"><SmilePlus size={14} /></button><button onClick={() => void report(message)} aria-label="Report"><Flag size={14} /></button>{message.sender_id === viewerId && <><button onClick={() => void edit(message)} aria-label="Edit"><Edit3 size={14} /></button><button onClick={() => void remove(message)} aria-label="Delete"><Trash2 size={14} /></button></>}</div></article>)}{!messages.length && <div className="empty-chat"><h2>Your conversation starts here.</h2><p>Messages are visible only to this conversation’s participants.</p></div>}<div ref={bottomRef} /></div><footer className="composer">{reply && <div className="reply-banner"><span>Replying to {reply.profiles?.display_name}</span><button onClick={() => setReply(null)}>Cancel</button></div>}{typing && <span className="typing-note">{other?.display_name || "Your friend"} is typing…</span>}{error && <p className="composer-error">{error}</p>}<form onSubmit={send}><textarea aria-label="Direct message" value={content} onChange={(event) => { setContent(event.target.value); announceTyping(); }} maxLength={2000} rows={1} placeholder={`Message ${other?.display_name || "conversation"}`} /><span>{content.length}/2000</span><button className="send-button" disabled={!content.trim()} aria-label="Send message"><Send size={17} /></button></form></footer></div>;
}
