"use client";

import { Check, Search, UserMinus, UserPlus, Users, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Avatar } from "@/components/app-frame";
import { createClient } from "@/lib/supabase/client";

type Person = { id: string; username: string; display_name: string; avatar_url: string | null; status?: string };
type Request = { id: string; requester_id: string; addressee_id: string; status: string; requester: Person; addressee: Person };
export function FriendsManager() {
  const supabase = useMemo(() => createClient(), []); const [viewerId, setViewerId] = useState(""); const [friends, setFriends] = useState<Person[]>([]); const [requests, setRequests] = useState<Request[]>([]); const [results, setResults] = useState<Person[]>([]); const [query, setQuery] = useState(""); const [notice, setNotice] = useState(""); const [guest, setGuest] = useState(false);
  const load = useCallback(async () => { if (!supabase) return; const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; if (auth.user.is_anonymous) { setGuest(true); return; } setViewerId(auth.user.id); const [{ data: friendData }, { data: requestData }] = await Promise.all([supabase.rpc("get_friends"), supabase.from("friend_requests").select("id,requester_id,addressee_id,status,requester:profiles!friend_requests_requester_id_fkey(id,username,display_name,avatar_url),addressee:profiles!friend_requests_addressee_id_fkey(id,username,display_name,avatar_url)").eq("status", "pending")]); setFriends((friendData as Person[]) ?? []); setRequests((requestData as unknown as Request[]) ?? []); }, [supabase]);
  useEffect(() => { void load(); }, [load]);
  async function find(value: string) { setQuery(value); if (!supabase || value.trim().length < 2) { setResults([]); return; } const { data } = await supabase.from("profiles").select("id,username,display_name,avatar_url,status").or(`username.ilike.%${value.trim()}%,display_name.ilike.%${value.trim()}%`).neq("id", viewerId).limit(8); setResults((data as Person[]) ?? []); }
  async function send(person: Person) { if (!supabase || !viewerId) { setNotice("Sign in to send a friend request."); return; } const { error } = await supabase.from("friend_requests").insert({ requester_id: viewerId, addressee_id: person.id }); setNotice(error ? (error.code === "23505" ? "A request already exists between you." : error.message) : `Request sent to ${person.display_name}.`); await load(); }
  async function decide(request: Request, status: "accepted" | "declined") { if (!supabase) return; const { error } = await supabase.from("friend_requests").update({ status, responded_at: new Date().toISOString() }).eq("id", request.id).eq("addressee_id", viewerId); setNotice(error?.message || (status === "accepted" ? "Friend added." : "Request declined.")); await load(); }
  async function remove(person: Person) { if (!supabase || !confirm(`Remove ${person.display_name} from your friends?`)) return; const { error } = await supabase.from("friendships").delete().or(`and(user_a.eq.${viewerId},user_b.eq.${person.id}),and(user_a.eq.${person.id},user_b.eq.${viewerId})`); setNotice(error?.message || "Friend removed."); await load(); }
  if (!supabase) return <div className="state-card error-state"><Users /><strong>The friend graph is ready for Supabase.</strong><p>Connect the database to activate requests and online friends.</p></div>;
  if (guest) return <div className="state-card"><Users /><strong>Create an account to add friends.</strong><p>You can keep chatting in public rooms as a temporary guest.</p><a className="primary-button" href="/sign-up">Create account</a></div>;
  return <div className="friends-layout">{notice && <div className="notice" role="status">{notice}</div>}<section className="manager-section"><div className="manager-heading"><div><span className="kicker">People</span><h2>Find someone</h2></div></div><label className="people-search"><Search size={17} /><input value={query} onChange={(event) => void find(event.target.value)} placeholder="Search by name or @username" /></label><div className="people-list">{results.map((person) => <div className="person-row" key={person.id}><Avatar name={person.display_name} image={person.avatar_url} /><div><a href={`/profile/${person.username}`}>{person.display_name}</a><span>@{person.username}</span></div><button onClick={() => void send(person)}><UserPlus size={15} /> Add</button></div>)}</div></section><section className="manager-section"><div className="manager-heading"><div><span className="kicker">Waiting for you</span><h2>Pending requests</h2></div><span>{requests.filter((item) => item.addressee_id === viewerId).length}</span></div><div className="people-list">{requests.filter((item) => item.addressee_id === viewerId).map((request) => <div className="person-row" key={request.id}><Avatar name={request.requester.display_name} image={request.requester.avatar_url} /><div><strong>{request.requester.display_name}</strong><span>@{request.requester.username}</span></div><button onClick={() => void decide(request, "accepted")}><Check size={15} /> Accept</button><button className="subtle-action" onClick={() => void decide(request, "declined")}><X size={15} /></button></div>)}{!requests.some((item) => item.addressee_id === viewerId) && <p className="empty-line">No pending requests.</p>}</div></section><section className="manager-section span-full"><div className="manager-heading"><div><span className="kicker">Your circle</span><h2>Friends</h2></div><span>{friends.length}</span></div><div className="friend-grid">{friends.map((person) => <div className="friend-card" key={person.id}><Avatar name={person.display_name} image={person.avatar_url} /><div><a href={`/profile/${person.username}`}>{person.display_name}</a><span>@{person.username}</span></div><i className={`status-dot ${person.status}`} /><button onClick={() => void remove(person)} aria-label={`Remove ${person.display_name}`}><UserMinus size={15} /></button></div>)}{!friends.length && <p className="empty-line">Your friends will appear here.</p>}</div></section></div>;
}
