"use client";

import { Ban, CalendarDays, Edit3, Flag, MessageCircle, Save, UserMinus, UserPlus, VolumeX } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Avatar } from "@/components/app-frame";
import { createClient } from "@/lib/supabase/client";
import { profileUpdateSchema } from "@/lib/schemas";

type Profile = { id: string; username: string; display_name: string; avatar_url: string | null; bio: string | null; status: string; created_at: string };
export function ProfileView({ username }: { username?: string }) {
  const router = useRouter(); const supabase = useMemo(() => createClient(), []); const [profile, setProfile] = useState<Profile | null>(null); const [viewerId, setViewerId] = useState(""); const [editing, setEditing] = useState(false); const [notice, setNotice] = useState(""); const [blocked, setBlocked] = useState(false); const [muted, setMuted] = useState(false); const [guest, setGuest] = useState(false);
  useEffect(() => { if (!supabase) return; void supabase.auth.getUser().then(async ({ data }) => { setGuest(Boolean(data.user?.is_anonymous)); setViewerId(data.user?.id ?? ""); let query = supabase.from("profiles").select("id,username,display_name,avatar_url,bio,status,created_at"); query = username ? query.eq("username", username) : query.eq("id", data.user?.id ?? "00000000-0000-0000-0000-000000000000"); const { data: found } = await query.maybeSingle(); setProfile(found); if (data.user && !data.user.is_anonymous && found && data.user.id !== found.id) { const [{ data: block }, { data: mute }] = await Promise.all([supabase.from("blocks").select("blocker_id").eq("blocker_id", data.user.id).eq("blocked_id", found.id).maybeSingle(), supabase.from("user_mutes").select("muter_id").eq("muter_id", data.user.id).eq("muted_id", found.id).maybeSingle()]); setBlocked(Boolean(block)); setMuted(Boolean(mute)); } }); }, [supabase, username]);
  async function startMessage() { if (!supabase || !profile || !viewerId) { setNotice("Sign in to send a message."); return; } const { data, error } = await supabase.rpc("get_or_create_direct_conversation", { other_user: profile.id }); if (error) setNotice(error.message); else router.push(`/messages/${data}`); }
  async function friend() { if (!supabase || !profile || !viewerId) return setNotice("Sign in to add friends."); const { error } = await supabase.from("friend_requests").insert({ requester_id: viewerId, addressee_id: profile.id }); setNotice(error ? "A request already exists between you." : "Friend request sent."); }
  async function toggleBlock() { if (!supabase || !profile || !viewerId) return; const result = blocked ? await supabase.from("blocks").delete().eq("blocker_id", viewerId).eq("blocked_id", profile.id) : await supabase.from("blocks").insert({ blocker_id: viewerId, blocked_id: profile.id }); if (!result.error) setBlocked(!blocked); else setNotice(result.error.message); }
  async function toggleMute() { if (!supabase || !profile || !viewerId) return; const result = muted ? await supabase.from("user_mutes").delete().eq("muter_id", viewerId).eq("muted_id", profile.id) : await supabase.from("user_mutes").insert({ muter_id: viewerId, muted_id: profile.id }); if (!result.error) setMuted(!muted); else setNotice(result.error.message); }
  async function report() { if (!supabase || !profile || !viewerId) return setNotice("Sign in to report an account."); const reason = prompt("Tell the moderation team what happened (at least 10 characters)."); if (!reason || reason.trim().length < 10) return; const { error } = await supabase.from("reports").insert({ reporter_id: viewerId, reported_user_id: profile.id, reason }); setNotice(error?.message || "Report sent privately to the moderation team."); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !profile) return; const form = new FormData(event.currentTarget); let avatarUrl = String(form.get("avatarUrl") ?? ""); const avatar = form.get("avatarFile"); if (avatar instanceof File && avatar.size) { if (avatar.size > 2_097_152 || !["image/jpeg", "image/png", "image/webp", "image/gif"].includes(avatar.type)) return setNotice("Avatar must be a JPG, PNG, WebP, or GIF under 2 MB."); const extension = avatar.name.split(".").pop()?.toLowerCase() || "jpg"; const path = `${profile.id}/${crypto.randomUUID()}.${extension}`; const upload = await supabase.storage.from("avatars").upload(path, avatar, { contentType: avatar.type, upsert: false }); if (upload.error) return setNotice(upload.error.message); avatarUrl = supabase.storage.from("avatars").getPublicUrl(path).data.publicUrl; } const parsed = profileUpdateSchema.safeParse({ username: form.get("username"), displayName: form.get("displayName"), bio: form.get("bio"), avatarUrl }); if (!parsed.success) return setNotice(parsed.error.issues[0]?.message || "Check your profile."); const { error } = await supabase.from("profiles").update({ username: parsed.data.username, display_name: parsed.data.displayName, bio: parsed.data.bio, avatar_url: parsed.data.avatarUrl || null, updated_at: new Date().toISOString() }).eq("id", profile.id); setNotice(error?.message || "Profile saved."); if (!error) { setProfile({ ...profile, username: parsed.data.username, display_name: parsed.data.displayName, bio: parsed.data.bio, avatar_url: parsed.data.avatarUrl || null }); setEditing(false); } }
  if (!supabase) return <div className="state-card error-state"><strong>Profiles are ready for Supabase.</strong><p>Connect the database to activate accounts.</p></div>; if (guest) return <div className="state-card"><strong>Create an account for member profiles.</strong><p>Your temporary guest identity is ready for public-room chat.</p><a className="primary-button" href="/sign-up">Create account</a></div>; if (!profile) return <div className="state-card"><strong>{username ? "Profile not found." : "Sign in to view your profile."}</strong>{!username && <a className="primary-button" href="/sign-in">Sign in</a>}</div>;
  const own = profile.id === viewerId;
  return <section className="profile-card"><div className="profile-cover"><span /><span /></div><div className="profile-main"><Avatar name={profile.display_name} image={profile.avatar_url} /><div className="profile-identity"><div><h1>{profile.display_name}</h1><span>@{profile.username}</span></div><i className={`presence-badge ${profile.status}`}><b /> {profile.status}</i></div>{notice && <div className="notice">{notice}</div>}{editing ? <form className="profile-form" onSubmit={save}><label>Display name<input name="displayName" defaultValue={profile.display_name} /></label><label>Username<input name="username" defaultValue={profile.username} /></label><label className="full">Bio<textarea name="bio" defaultValue={profile.bio ?? ""} maxLength={240} /></label><label>Avatar URL<input name="avatarUrl" type="url" defaultValue={profile.avatar_url ?? ""} /></label><label>Upload avatar<input name="avatarFile" type="file" accept="image/jpeg,image/png,image/webp,image/gif" /></label><div className="full form-actions"><button type="button" className="secondary-button" onClick={() => setEditing(false)}>Cancel</button><button className="primary-button"><Save size={15} /> Save profile</button></div></form> : <><p className="profile-bio">{profile.bio || (own ? "Add a short bio so people know what you’re curious about." : "This member hasn’t added a bio yet.")}</p><div className="profile-meta"><CalendarDays size={15} /> Joined {new Date(profile.created_at).toLocaleDateString([], { month: "long", year: "numeric" })}</div></>}{own ? <button className="primary-button profile-primary" onClick={() => setEditing(true)}><Edit3 size={15} /> Edit profile</button> : <div className="profile-actions"><button className="primary-button" onClick={() => void startMessage()}><MessageCircle size={15} /> Message</button><button className="secondary-button" onClick={() => void friend()}><UserPlus size={15} /> Add friend</button><button className="secondary-button" onClick={() => void toggleMute()}>{muted ? <UserMinus size={15} /> : <VolumeX size={15} />}{muted ? "Unmute" : "Mute"}</button><button className="danger-button" onClick={() => void toggleBlock()}><Ban size={15} /> {blocked ? "Unblock" : "Block"}</button><button className="icon-button" onClick={() => void report()} aria-label="Report user"><Flag size={15} /></button></div>}</div></section>;
}
